CREATE TABLE IF NOT EXISTS persons (
    person_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_host varchar(50) NOT NULL,
    last_modified_host varchar(50),
    created_user varchar(50) NOT NULL,
    last_modified_user varchar(50),
    created_date timestamp NOT NULL,
    last_modified_date timestamp,
    status boolean NOT NULL,
    identification varchar(10) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    lastname varchar(255) NOT NULL,
    address varchar(255),
    telephone varchar(10),
    gender char(1),
    age integer
);

CREATE TABLE IF NOT EXISTS roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_host varchar(50) NOT NULL,
    last_modified_host varchar(50),
    created_user varchar(50) NOT NULL,
    last_modified_user varchar(50),
    created_date timestamp NOT NULL,
    last_modified_date timestamp,
    status boolean NOT NULL,
    name varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_host varchar(50) NOT NULL,
    last_modified_host varchar(50),
    created_user varchar(50) NOT NULL,
    last_modified_user varchar(50),
    created_date timestamp NOT NULL,
    last_modified_date timestamp,
    status boolean NOT NULL,
    password varchar(60) NOT NULL,
    username varchar(20) NOT NULL UNIQUE,
    person_id bigint NOT NULL REFERENCES persons(person_id)
);

CREATE TABLE IF NOT EXISTS role_users (
    role_user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_host varchar(50) NOT NULL,
    last_modified_host varchar(50),
    created_user varchar(50) NOT NULL,
    last_modified_user varchar(50),
    created_date timestamp NOT NULL,
    last_modified_date timestamp,
    status boolean NOT NULL,
    rol_id bigint NOT NULL REFERENCES roles(role_id),
    user_id bigint NOT NULL REFERENCES users(user_id),
    CONSTRAINT uk_role_users_role_user UNIQUE (rol_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_users_person_id ON users(person_id);
CREATE INDEX IF NOT EXISTS idx_role_users_user_id ON role_users(user_id);
CREATE INDEX IF NOT EXISTS idx_role_users_rol_id ON role_users(rol_id);

CREATE TABLE IF NOT EXISTS oauth2_registered_client (
    id varchar(100) NOT NULL PRIMARY KEY,
    client_id varchar(100) NOT NULL,
    client_id_issued_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret varchar(200),
    client_secret_expires_at timestamp,
    client_name varchar(200) NOT NULL,
    client_authentication_methods varchar(1000) NOT NULL,
    authorization_grant_types varchar(1000) NOT NULL,
    redirect_uris varchar(1000),
    post_logout_redirect_uris varchar(1000),
    scopes varchar(1000) NOT NULL,
    client_settings varchar(2000) NOT NULL,
    token_settings varchar(2000) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_oauth2_registered_client_client_id
    ON oauth2_registered_client(client_id);

CREATE TABLE IF NOT EXISTS oauth2_authorization (
    id varchar(100) NOT NULL PRIMARY KEY,
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorization_grant_type varchar(100) NOT NULL,
    authorized_scopes varchar(1000),
    attributes text,
    state varchar(500),
    authorization_code_value text,
    authorization_code_issued_at timestamp,
    authorization_code_expires_at timestamp,
    authorization_code_metadata text,
    access_token_value text,
    access_token_issued_at timestamp,
    access_token_expires_at timestamp,
    access_token_metadata text,
    access_token_type varchar(100),
    access_token_scopes varchar(1000),
    oidc_id_token_value text,
    oidc_id_token_issued_at timestamp,
    oidc_id_token_expires_at timestamp,
    oidc_id_token_metadata text,
    refresh_token_value text,
    refresh_token_issued_at timestamp,
    refresh_token_expires_at timestamp,
    refresh_token_metadata text,
    user_code_value text,
    user_code_issued_at timestamp,
    user_code_expires_at timestamp,
    user_code_metadata text,
    device_code_value text,
    device_code_issued_at timestamp,
    device_code_expires_at timestamp,
    device_code_metadata text
);

CREATE TABLE IF NOT EXISTS oauth2_authorization_consent (
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorities varchar(1000) NOT NULL,
    PRIMARY KEY (registered_client_id, principal_name)
);